#!/bin/zsh
TODO="Dnd Documents Go GuoJuan MikesDots"
for f in `echo $TODO | grep -o "\w*"`
do
  OUT=~/backups/$f.bak    
  rsync -ah --progress --inplace $f $OUT
done
rsync -ah --progress --inplace -e ssh ~/backups k.cs.uiuc.edu:~/backups